### ISSUE TITLE
upload parallelization

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/upload-service#103]
Be able to upload more than one file simultaneously.  Although individual file transfer is unlikely to go faster as you're bottlenecked by your internet connection, it does reduce the downtime between uploads.

**Comment by parthshahva** [comment]
Need to research what boto3 functionality currently exists

**Comment by parthshahva** [comment]
@sampierson I did some research on this topic. It appears boto3 does not have native support for parallel upload of files. The current method we invoke provides multithreaded/multi-part support for a single file. awscli on the other hand wraps all s3 commands into a queue + thread pool. Adding a threadpool + queue + changing how we manage progress updates will probably get us a 2x improvement on file upload. Does this sound about right for implementation?
