### ISSUE TITLE
Batch clusters do not work until you add security group ssh-access-from-anywhere

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/upload-service#105]
The workers do not register with the ECS cluster.
It makes no sense that inbound SSH access would make a difference, but that is the behavior I have observed.

**Comment by parthshahva** [comment]
Need to replicate in an environment

**Comment by parthshahva** [comment]
@sampierson have you seen this since the last time we saw it in production? I have tried spinning down and bring up batch infra to replicate but batch works without any problems when doing this. Unless we are able to replicate, I will mark this as closed

**Comment by sampierson** [comment]
Last time I was this I was bringing up a new environment (predev).  I expect you will see it again the next time we spin up an environment.

**Comment by sampierson** [comment]
However, we don't do that very often, so I'd leave this in the icebox.
