### ISSUE TITLE
The CI build doesn't fail if part of the deploy fails

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/upload-service#106]
e.g. https://travis-ci.org/HumanCellAtlas/upload-service/builds/394639820

**Comment by parthshahva** [comment]
If deploy fails, travis build needs to be marked as red.

**Comment by kislyuk** [comment]
`https://github.com/HumanCellAtlas/upload-service/blob/master/scripts/deploy.sh` (and all shell scripts) should always `set -euo pipefail`.

**Comment by sampierson** [comment]
Andrey's suggestion fixed this.
