### ISSUE TITLE
schedule_fastq_validation.py fails to schedule files

### ISSUE THREAD

**Issue by hewgreen** [HumanCellAtlas/upload-service#115]
Upon running these commands in the wranglers ec2:

```
python /data/tools/schedule_fastq_validation.py --upload-area-id aaaaaaaa-bbbb-cccc-dddd-39f84579ab8c --api-key SENT_VIA_SLACK --dataset-name mgreen-pancreas6decades-staging-0
```

For every file I get 'failed to schedule'.

```
python /data/tools/schedule_fastq_validation.py --upload-area-id aaaaaaaa-bbbb-cccc-dddd-5f46515b9467 --api-key SENT_VIA_SLACK --dataset-name mgreen-ido_amit-staging-0
```

This one works now but failed earlier today. Mallory also tried a working command on one of her repos and this also failed earlier today.

**Comment by sampierson** [comment]
That is a pretty vague error message.  Could the `schedule_fastq_validation.py` script be modified to display the error it received when trying to schedule?

**Comment by hewgreen** [comment]
I just had another go and got the same message. Can you replicate this Sam?

**Comment by parthshahva** [comment]
I am able to replicate this. I'll take a look today

**Comment by parthshahva** [comment]
@hewgreen I was able to schedule and retrieve validation for the 25 fastq files in the second area you listed. However, the first command is pointing to an upload area id that has 0 files in the s3 bucket. The files only exist on the ec2. Were these files manually dropped on to the ec2? In order to schedule validations, the files need to exist in the relevant s3 bucket (loaded in via the hca client)

Curious if @malloryfreeberg could add any dataset names/upload_area_ids she had problems with and whether they follow same pattern of the files only existing on the ec2

**Comment by parthshahva** [comment]
{code}
AB2314.fastq.gz: VALID
AB2690.fastq.gz: VALID
AB2301.fastq.gz: VALID
AB4735.fastq.gz: VALID
AB2302.fastq.gz: VALID
AB2149.fastq.gz: VALID
AB2312.fastq.gz: VALID
AB2150.fastq.gz: VALID
AB2829.fastq.gz: VALID
AB2837.fastq.gz: VALID
AB2136.fastq.gz: VALID
AB4616.fastq.gz: VALID
AB3065.fastq.gz: VALID
AB4617.fastq.gz: VALID
AB2306.fastq.gz: VALID
AB2695.fastq.gz: VALID
AB2137.fastq.gz: VALID
AB4653.fastq.gz: VALID
AB2138.fastq.gz: VALID
AB2303.fastq.gz: VALID
AB3066.fastq.gz: VALID
AB4736.fastq.gz: VALID
AB2307.fastq.gz: VALID
AB2835.fastq.gz: VALID
AB2313.fastq.gz: VALID
{code}

**Comment by parthshahva** [comment]
I've updated the script to return better errors:

```
failed to schedule SRR3562252_2.fastq.gz for validation with status code 404 and error: No such file
failed to schedule SRR3562664_1.fastq.gz for validation with status code 404 and error: No such file
failed to schedule SRR3562907_1.fastq.gz for validation with status code 404 and error: No such file
failed to schedule SRR3563972_1.fastq.gz for validation with status code 404 and error: No such file
failed to schedule SRR3563494_2.fastq.gz for validation with status code 404 and error: No such file
failed to schedule SRR3564035_2.fastq.gz for validation with status code 404 and error: No such file
failed to schedule SRR3563394_2.fastq.gz for validation with status code 404 and error: No such file
failed to schedule SRR3563081_2.fastq.gz for validation with status code 404 and error: No such file
failed to schedule SRR3564648_1.fastq.gz for validation with status code 404 and error: No such file
failed to schedule SRR3563492_1.fastq.gz for validation with status code 404 and error: No such file
failed to schedule SRR3563693_2.fastq.gz for validation with status code 404 and error: No such file
failed to schedule SRR3563964_1.fastq.gz for validation with status code 404 and error: No such file
failed to schedule SRR3564598_2.fastq.gz for validation with status code 404 and error: No such file
```

This is an example of output with mgreen-pancreas6decades-staging-0 dataset since data only lives on ec2 and not in the s3 bucket at the moment

**Comment by hewgreen** [comment]
That makes sense. The working one was uploaded by a user with the hca client but the other is from a published dataset. We have a few datasets that are already published in public repos and are quite large (Chris has a few TB for his tabular munis dataset). So we are transferring these into the ec2 manually.

I'm open to other suggestions but can we get the files into the s3 bucket from the ec2 to solve this problem or add a feature to the hca client to take a list of ftp links and get the files from public repos?

**Comment by parthshahva** [comment]
Improving the hca client to accept ftp links is definitely not on the pre-MVP radar, so I would continue with your script. I will create the feature request and add it to the board. 

I would recommend you use the hca client to sync these files to their respective buckets in order to be able to run validation on them using the upload/batch infrastructure.

**Comment by parthshahva** [comment]
TIcket created to track feature request for being able to stage files from ftp urls. Closing this issue as path forward exists with current tooling, ie upload files to relevant bucket using hca client.
