### ISSUE TITLE
Fix functional test to be able to be run against production

### ISSUE THREAD

**Issue by parthshahva** [HumanCellAtlas/upload-service#120]

**Comment by sampierson** [comment]
When running with AWS_PROFILE=hca-prod, which you need to be able to run the functional tests, you need access to the 4GB file at `s3://org-humancellatlas-dcp-test-data/upload_service/4097MB_file`.

I granted read access to that file to the prod account (using its canonical user ID).
To find the canonical user ID you use `aws s3api list-buckets`
