### ISSUE TITLE
Issue with file validation scheduling when hash in name

### ISSUE THREAD

**Issue by parthshahva** [HumanCellAtlas/upload-service#138]
```python /data/tools/schedule_fastq_validation.py --upload-area-id aaaaaaaa-bbbb-cccc-dddd-13f7d1fd7f8c --api-key 0FdyOclZKxcWmgtzoXqQEbW11EQ4HG/NWqrc7XyPAUoGs2u6VMy+PCDfxqakO+euu1qw2cDKu9z1KRwjR1ZYIdO8bcbE1lf73nmUOoTooZy6wtuiTBaCaiqQb0HF+/5w5J8O5CS1rvOBovEh3nD6MyRk/FosyfTWuM9FwHN0PDc= --dataset-name mfreeberg-teichmann-staging-0
failed to schedule 22028_3#364_1.fastq.gz for validation with status code 400 and error: Invalid Content-Type
failed to schedule 22028_2#90_2.fastq.gz for validation with status code 400 and error: Invalid Content-Type
failed to schedule 22421_8#50_1.fastq.gz for validation with status code 400 and error: Invalid Content-Type
...```

The `schedule_fastq_validation.py` script works fine for another upload area I have. I wonder if there is an issue with the hash being in the filename? I know this was a problem during the preview release, and SamP had to implement a workaround to get those files to validate because the hash was throwing off the URL.

**Comment by parthshahva** [comment]
@sampierson I realized today we'll need to add the same hash escape solution to the docker images when they call back out to upload api for checksum and validation for this to fully work and unblock @malloryfreeberg on this upload area. Is this worthy of applying a hotfix onto staging and rebase validation image of new base image immediately? Or should we go the normal route of code promotion?

**Comment by sampierson** [comment]
Progress trumps process.  Do the hotfix.

A related thought: we should be building the docker images automatically as a part of CI.  Perhaps using quay.io.  We should create a ticket for that.

The AMI is harder to build automatically, but that's a problem for a different day.
