### ISSUE TITLE
create prod grafana dashboard

### ISSUE THREAD

**Issue by parthshahva** [HumanCellAtlas/upload-service#149]
Involves adding grafana datasource with access to prod database

**Comment by parthshahva** [comment]
Eduardo is updating fogg to allow use of jq as a custom binary. Waiting for that to complete to finish this task

**Comment by parthshahva** [comment]
{code}
[1m[31mError: [0m[0m[1mError asking for user input: 1 error(s) occurred:

* module.env-dashboards.local.dss_dashboard: local.dss_dashboard: 1154:24: unknown variable accessed: var.aws_logs_data_source_name in:
{code}

@mweiden This ticket is blocked from this error when running make apply in terraform/envs/prod/env-dashboards on dcp-monitoring master. Any thoughts? It worked fine for dev/integration/staging

**Comment by mweiden** [comment]
@parthshahva I fixed the problem, applied, and uploaded [your dashboard](https://metrics.data.humancellatlas.org/d/upload-prod/upload-prod?refresh=1m&orgId=1).

Closing this ticket.
