### ISSUE TITLE
hca upload file: too many messages to screen

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/upload-service#159]
On tool.staging.data.hca.org, using hca 0.0.0 (CPython 2.7.12 Linux-4.4.0-1062-aws-x86_64-with-Ubuntu-16.04-xenial), I ran `hca upload select <area>` and `hca upload file *.fastq.gz` and am then pelted with a lot of progress messages to the screen (screenshot below). 

Could the messages of progress per file be overwritten instead of appended to the screen?

Showing the "Download complete..." and "...1551 of 2317 files remaining" bits is helpful, but there are just too many messages sent to the screen to actually read any of it.

![screen shot 2018-08-22 at 11 54 08](https://user-images.githubusercontent.com/10993501/44459759-ae58ca00-a602-11e8-9fc8-b30b6bbe8163.png)

**Comment by parthshahva** [comment]
- fix download to upload
- set threshold to 1 second from callback

High priority as requested by @malloryfreeberg
