### ISSUE TITLE
Rebuild Upload AMI

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/upload-service#164]
As is often the case, ECS is complaining that our validation cluster instances contain an out-of-date agent.  We should rebuild the AMI, which we need to do periodically.

![Screen Shot 2018-08-29 at 2.35.44 PM.png](https://images.zenhubusercontent.com/5aba7bf14b5806bc2bcca343/d770a3f1-3d36-4585-a9c5-b40616b7b2f9)

**Comment by parthshahva** [comment]
@parthshahva Schedule a screen share party to get this done

**Comment by parthshahva** [comment]
@sampierson It would be nice if you were able to do this and document the instructions in allspark

**Comment by sampierson** [comment]
The instructions on how to do it are in the README https://github.com/HumanCellAtlas/upload-service/blob/master/amis/README.md

**Comment by sampierson** [comment]
AMI created - `ami-0939b827b1bf145c9`.

https://github.com/HumanCellAtlas/upload-service/pull/347
