### ISSUE TITLE
Write script to clean up/delete upload areas in db + buckets

### ISSUE THREAD

**Issue by parthshahva** [HumanCellAtlas/upload-service#192]

**Comment by parthshahva** [comment]
Notes from a slack convo with SamP

1) Delete any records for files we no longer have.  At the end we have a database that mirrors exactly which files actually exist in S3.
2) Delete all files for upload areas in "DELETING" status and then remove the db records in cases where delete lambda timed out
3) Remove all s3 objects that have no references in db (probably uploaded prior to this tracking setup)

**Comment by sampierson** [comment]
I think I've only done 1 and 2 so far.  3 is still TBD.

**Comment by parthshahva** [comment]
Dev and Integration s3 + db were wiped clean. Script completed on staging that deleted all objects from s3 that were not specially designated by wranglers. New ticket created to wipe out prod db + s3 after tabula muris finishes exporting bundles.
