### ISSUE TITLE
Gitlab deployment for all environments (5 steps)

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/upload-service#20]
For all 4 environments the following should be moved into gitlab
1) make test
2) run functional tests if environment branch
3) terraform check => fail out if infra is out of date
4) deployment
5) run functional tests again

**Comment by parthshahva** [comment]
As part of this task, get production functional test running in gitlab

**Comment by sampierson** [comment]
I don't understand step 2.  Functional tests test the deployed code. What's the point of testing the old deployed code before you deploy the new?  I guess this could catch some external dependency failures, like we encountered last week with out role policies being deleted.

**Comment by parthshahva** [comment]
Hmmm, I can see it both ways. I was thinking that there is value in knowing the environment is functional at the exact moment prior to deploying. If the second functional test fails, we now can be pretty sure that its related to the most recent deployment

**Comment by sampierson** [comment]
There is definitely value in knowing the environment is functional at the exact moment prior to deploying, however if we implement our plan to run functional tests daily, that will mostly take care of this, and won't slow down deployments.
