### ISSUE TITLE
Validator reports `No such file or directory` for allegedly staged file

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/upload-service#205]
Rolando says "The validator is reporting this error: `ERROR: Unable to open /data/4baab460-6282-42e8-aa90-44249c84cb2e/pbmc4k_S1_L001_R2_001.fastq.gz`. At a guess, the file isn’t ready at the mount point in the batch instance when the validator image starts?"

**Comment by sampierson** [comment]
Submission 5bd2c9c3f31a6a000726f72d

**Comment by sampierson** [comment]
I improved `dcpdig` to do database mining.  
`dcpdig -d staging @upload file_id=4baab460-6282-42e8-aa90-44249c84cb2e/pbmc4k_S1_L001_R2_001.fastq.gz --show all --verbose`
Reveals 2 checksum, 4 validation and 6 notification records (2 checksum notifications, 4 validation notifications).
All of the validation records have state "VALIDATED", however check out the payload on this record:
```	Validation 65036700-b1eb-49f9-be98-c0fd7e5a5491
	                  File ID: 4baab460-6282-42e8-aa90-44249c84cb2e/pbmc4k_S1_L001_R2_001.fastq.gz
	                   Job ID: 3cf3a140-d01d-40ef-b63e-4df10d4d6822
	                   Status: VALIDATED
	    validation_started_at: 2018-10-26 08:06:34.078748+00:00
	      validation_ended_at: 2018-10-26 08:06:34.306447+00:00
	               created_at: 2018-10-26 08:01:37.949321+00:00
	               updated_at: 2018-10-26 08:06:34.306450+00:00
	                  results: {'name': 'pbmc4k_S1_L001_R2_001.fastq.gz', 'status': 'completed', 'stderr': '', 'stdout': '{"validation_state": "INVALID", "validation_errors": [{"user_friendly_message": "ERROR: Unable to open /data/4baab460-6282-42e8-aa90-44249c84cb2e/pbmc4k_S1_L001_R2_001.fastq.gz"}]}\n', 'command': '/validator /data/4baab460-6282-42e8-aa90-44249c84cb2e/pbmc4k_S1_L001_R2_001.fastq.gz', 'exception': None, 'exit_code': 0, 'duration_s': 0.05190873146057129, 'validation_id': '3cf3a140-d01d-40ef-b63e-4df10d4d6822', 'upload_area_id': '4baab460-6282-42e8-aa90-44249c84cb2e'}```

**Comment by parthshahva** [comment]
We believe this is due to wrangler impatience in scheduling two validations on the same job. One removed the file before the other completed.

**Comment by parthshahva** [comment]
Reopening. Seen again on 10/31. `ERROR: Unable to open /data/d3af8cd2-f8c0-41e7-80b7-3736af89407a/R2.fastq.gz`

**Comment by sampierson** [comment]
Seen again in 11/1: `ERROR: Unable to open /data/9c3f821b-9c27-4293-84c6-48abbdae97b9/R2.fastq.gz`
