### ISSUE TITLE
Manual sync from s3 to pilot data ec2

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/upload-service#216]
Why we need this?
We need the ability to manually sync from s3 to ec2 because currently ec2 is full. It wouldd be better if the s3 is the source of truth rather than ec2. We would also like to associate already populated s3 bucket to a new submission in ingest -  https://github.com/HumanCellAtlas/ingest-central/issues/241

Currently:
Direct data uploads via hca cli to an s3 bucket. When sync is triggered all active s3 buckets are synced to the ec2.
After the submission is submitted to the data store the s3 bucket is deleted.

What we would like:
Direct data uploads via hca cli to an s3 bucket. Ability to manually trigger sync for a specific s3 bucket to the ec2 if needed. We intend to do this sync to the ec2 when we need to do file manipulations, such as renaming files.
We would like to have the ability to manually sync from ec2 back to s3 bucket. This will be useful when we use Aspera to load files. Files can be deleted from the ec2 when they are fully synced to s3 bucket.

**Comment by parthshahva** [comment]
Action items:
@hewgreen to investigate clearing up ec2 and making staging s3 buckets as source of truth
@parthshahva to investigate adding support for s3 bucket url to hca upload cli

**Comment by hewgreen** [comment]
wranglers confirming which datasets are golden here. https://docs.google.com/spreadsheets/d/1uIzjswwIgqI_tg6F4jGu7IEUQpUoV2BiIEUycWvSeCw/edit#gid=0
