### ISSUE TITLE
To Timeout or not To Timeout in validator harness.py

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/upload-service#22]
When I first built the validation service, I included a timeout in `harness.py` that wraps the validators provided by Ingest, with the assumption that these things will occasionally hang.   This code never really worked (I think I didn't attempt to kill the validator aggressively enough), so I disabled it.

If we think having timeouts around validators is useful we should make this code work (we *have* seen validators hang).  Otherwise we should finish removing the code.

**Comment by maniarathi** [comment]
What's the status on this bug? Are there still cases where the validators hang (and therefore we should just fix the timeouts) or is this behavior unnecessary (and therefore we should remove the current broken timeout impl)?

**Comment by parthshahva** [comment]
I think we should have a 1 hour timeout in place for validation jobs. Anything more than that should lead to a failed batch job
