### ISSUE TITLE
Provide support for validation of paired fastqs

### ISSUE THREAD

**Issue by parthshahva** [HumanCellAtlas/upload-service#237]
This ticket needs design discussion and requirement enumeration.

cc @sampierson 

See https://github.com/HumanCellAtlas/ingest-central/issues/134

**Comment by sampierson** [comment]
While using paths for API endpoints with `filename` in then is somewhat RESTful, e.g. `/v1/area/<uuid>/<filename>/validate`, it is serving us less and less well.  We should change the "schedule validation" endpoint to be `/area/<uuid>/validate` and add the files that you wish to validate to the payload.  Oh and to be at least minimally RESTful we should call it `validation`, e.g. `POST `/area/<uuid>/validation` schedules a validation and `GET `/area/<uuid>/validation/<validation_id>` gets you its status and results when ready. 

Or conceivably even do it as `/area/validate` or just `/validate` and add the area UUID to the payload also.

**Comment by sampierson** [comment]
Apart from that, we need to:
 * change the validation record to store a list of files instead a single one
 * get `harness.py` to stage and unstage multiple files
 * call the validator with multiple files as args

**Comment by parthshahva** [comment]
@justincc when do you think ingest will get to this? We will need to complete some upload work to enable this feature

**Comment by justincc** [comment]
This is in our current sprint. We need to understand it first (me perhaps more than the others) so is it sufficient to check in with you once we're ready to deploy?

**Comment by sampierson** [comment]
This is a feature that is going to require collaboration and coordination between Ingest and Upload.
You don't want to talk to us until you're ready to *deploy*?  How will that work?

**Comment by parthshahva** [comment]
Yea I think we need a discussion here around the interface enabling this before development on either side occurs

**Comment by rolando-ebi** [comment]
We still need to flesh out what exactly the wranglers are expecting here. Also need to determine the current validator's suitability. A conversation about interfaces will be more fruitful after that

**Comment by rolando-ebi** [comment]
> We should change the "schedule validation" endpoint to be `/area/<uuid>/validate` and add the files that you wish to validate to the payload. Oh and to be at least minimally RESTful we should call it `validation`, e.g. `POST /area/<uuid>/validation` schedules a validation and `GET /area/<uuid>/validation/<validation_id>` gets you its status and results when ready.

@sampierson @parthshahva This would work great for us. An example payload:

`
{
  "validation_image": "quay.io/....",
  "files" : ["R1.fastq.gz", "R2.fastq.gz", "ind.fastq.gz"]
}
`

We will use the returned validation job ID to mark R1.fastq.gz, R2.fastq.gz and ind.fastq.gz in our database. Note that the ordering of `"files"` should be preserved when passed as args to our validation image/script.
