### ISSUE TITLE
Don't notify Ingest during tests

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/upload-service#238]
Add a new Notification status ENUM value "DROPPED"
Drop notifications when the Upload Area ID starts with "deadbeef"

**Comment by parthshahva** [comment]
@maniarathi to link PR or update status

**Comment by maniarathi** [comment]
lol I think I was just hallucinating yesterday or just mixed this up with another bug I was working on.. I actually haven't even looked at this

**Comment by sampierson** [comment]
Maybe unassign yourself from it then, so someone else can pick it up?
