### ISSUE TITLE
Use Ingest API endpoints in sending file upload and file validation result messages

### ISSUE THREAD

**Issue by aaclan-ebi** [HumanCellAtlas/upload-service#245]
Hi Upload Service

We will soon remove the external access to our RabbitMQ queues. In line with this, the upload service will need to update how file upload info and file validation result are sent to us.

Instead of sending message payload to the the following RabbitMQ queues:
1. exchange: 'ingest.file.staged.exchange'
    queue: 'ingest.file.create.staged'
2. exchange: 'ingest.validation.exchange'
    queue: 'ingest.file.validation.queue'

same message payload must be POSTed to the new HTTP Ingest API endpoints:
1. https://api.ingest.dev.data.humancellatlas.org/messaging/fileUploadInfo
2. https://api.ingest.dev.data.humancellatlas.org/messaging/fileValidationResult

The changes are now available for testing in dev. 

Target dates for endpoints availability in:
integration: 09/01/2019
staging: 16/01/2019
prod: 23/01/2019

We'll remove access to RabbitMQ by 31/01/2019 (Target Date)

Please let us know if you have any questions.

Many thanks!

**Comment by aaclan-ebi** [comment]
Hi

Just want to add that we'll also secure these endpoints soon, you'll need to generate self-issued JWTs using the Google account credentials as described here https://allspark.dev.data.humancellatlas.org/dcp-ops/docs/wikis/Security/Authentication%20and%20Authorization/Setting%20up%20DCP%20Auth#sample-code and pass that token in the headers.

Thanks
Alegria

**Comment by aaclan-ebi** [comment]
Here's a sample request:
```
curl -v -H 'Content-Type: application/json' -H "Authorization: Bearer $TOKEN"  -X POST https://api.ingest.dev.data.humancellatlas.org/messaging/fileValidationResult -d '{"messageProtocol":null,"documentType":"submissionenvelope","documentId":"5c0fd4a1f37fbd4fdf5ecc51","documentUuid":"22f06985-4313-4837-b2a0-af13dea1d95a","callbackLink":"/submissionEnvelopes/5c0fd4a1f37fbd4fdf5ecc51"}'
```

**Comment by justincc** [comment]
@aaclan-ebi could we pause this briefly in the New Year so that we can talk about the new endpoints? I know we had a bit of discussion before I went away but this noob wants to feel assured that we are exposing this in the best manner possible.

**Comment by justincc** [comment]
Sorry forgot to tell you, we won't change the endpoints, please push to dev. Dates are correct unless @aaclan-ebi knows any different.

**Comment by justincc** [comment]
Is this in integration yet?
