### ISSUE TITLE
Update `schedule validation` to use with individual files rather than on a whole dataset.

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/upload-service#252]
As a data wrangler, I would like to be able to schedule validation of a specific file. 
Currently we use: 
`/data/tools/schedule_fastq_validation.py —upload-area-id upload_area_id —api-key api_key —dataset-name dataset-name`
I propose to use this command on an individual file or several files at a time rather than the whole dataset.

This will decrease the workload and costs of file validation and make it more efficient for both wranglers and upload-service.

**Comment by parthshahva** [comment]
As part of this need to remove the requirement for file to be on ec2 to validate it. File existing in the s3 bucket should be enough
