### ISSUE TITLE
Data files stuck in "validating" status in staging

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/upload-service#256]
93 fastq files from a CBeta dataset are currently stuck in "validating" status in staging:
31 files of ~3 GB 
31 files of ~8 GB
31 files of ~30GB

Submission ID (staging): 5c0a4f6fa73b170007f5c991

**Comment by parthshahva** [comment]
This was not an upload issue after all. fix has been PRed at https://github.com/HumanCellAtlas/fastq_utils/pull/6. Ingest devs should work with the wranglers to retry after the new image has been created post merge and ingest-validator config has been updated and deployed to dev
