### ISSUE TITLE
Fix pip install conflicts

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/upload-service#273]
When installing packages in a new virtualenv from scratch you see:
```
awscli 1.15.70 has requirement botocore==1.10.69, but you'll have botocore 1.12.44 which is incompatible.
hca 4.6.0 has requirement boto3<1.8,>=1.7, but you'll have boto3 1.9.44 which is incompatible.
```

**Comment by maniarathi** [comment]
I'm not sure this is possible. hca and awscli require different versions of botocore/boto3 which is what causes incompatibility. We could change hca requirements to require a different version of botocode/boto3 as an option.

**Comment by sampierson** [comment]
Two thoughts here:
1) why is hca a dependency of upload-service?  Can we remove that.

2) I would suggest you go test hca cli with the same version as awscli.  If it tests cleanly, switch hca to that version.

**Comment by parthshahva** [comment]
HCA is a dependency of upload-service because hca-cli is used in functional test runs to upload files

**Comment by maniarathi** [comment]
https://github.com/HumanCellAtlas/dcp-cli/pull/282 Pull request for hca to update the boto3 version.
