### ISSUE TITLE
Track down and eliminate upload areas with glioblastoma data

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/upload-service#282]

**Comment by parthshahva** [comment]
wiping dev and integration environments. keep special prefixes in staging. 
also confirm in prod (date based rule)

**Comment by parthshahva** [comment]
Dev and Integration s3 + db were wiped clean. Script completed on staging that deleted all objects from s3 that were not specially designated by wranglers. New ticket created to wipe out prod db + s3 after tabula muris finishes exporting bundles.
