### ISSUE TITLE
Fix non-deterministic unit test

### ISSUE THREAD

**Issue by parthshahva** [HumanCellAtlas/upload-service#336]
FAIL: test_init__doesnt_create_db_record_if_one_already_exists (tests.unit.common.test_uploaded_file.TestUploadedFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/HumanCellAtlas/upload-service/tests/unit/common/test_uploaded_file.py", line 109, in test_init__doesnt_create_db_record_if_one_already_exists
    self.assertEqual(record_count_before, self.db.query(DbFile).count())
AssertionError: 12935 != 12936

**Comment by sampierson** [comment]
Interestingly GitLab isn't failing at all.

**Comment by parthshahva** [comment]
Just took a look at the test. The test is checking to make sure we don't create another file record in the db if a file is uploaded with same key + etag. This will fail if another test run or process creates a file record while this test is running. It occurs in travis sometimes because 2 builds are kicked off for each PR while gitlab only kicks off 1 build per merge
We probably need to be more specific on the before and after query in the test to just check that another record with that s3 key wasn't created
