### ISSUE TITLE
Rewrite functional test to use hca upload client library

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/upload-service#355]
The Upload client library in the `hca` package has been rewritten to have more comprehensive coverage of the Upload API.  We should rewrite the Upload functional test to use the client library where we can, so as to give it some integration testing.

Probably use CLI where we have coverage, and Library where CLI doesn't go.

**Comment by maniarathi** [comment]
It seems like we largely use the hca library when possible; currently we use it to select an upload area, upload files to the upload area, and forget an upload area. Do you have some other behaviors in mind?

**Comment by sampierson** [comment]
We don't currently use the hca library, we call out to the command line and use the hca CLI.
Given that I have just added support for practically all Upload endpoints to the python library, I want to start using that to do the other steps, like create an upload area, etc.
