### ISSUE TITLE
Better checksumming

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/upload-service#37]
Client calculates checksums during upload.  Server verifies client-provided checksums.

(Feature “Submitter can crypto-confirm file was staged with integrity”).

**Comment by parthshahva** [comment]
@sampierson @parthshahva to define with better requirements

**Comment by maniarathi** [comment]
Tasks
- [ ] Figure out which one of the four tasks to generate client-side (needs to be fast, etag potentially if we can figure out how to generate them the same way both times, etc.)
- [ ] Implement client-side checksumming generating above checksum
- [ ] Attach value to the metadata of the file that is being uploaded as a key-value pair
- [ ] Upload as normal
- [ ] Verify that server-side checksum is the same as the client-side checksum

**Comment by ttung** [comment]
In the distant past, it was suggested that the client would only calculate one of the four checksums.  I think that it's so computationally cheap that we should actually calculate all four checksums client-side.  The cost is mostly I/O, and that's amortized across four checksum comptations.
