### ISSUE TITLE
Integration tests may still leave bundles behind

### ISSUE THREAD

**Issue by jessebrennan** [HumanCellAtlas/upload-service#384]
To decide which bundles to delete, the integration tests looks at the bundles that were indexed, and deletes those. Deletion notifications should be sent for all of the bundles.

**Comment by parthshahva** [comment]
@jessebrennan why did you create this in the upload service? It sounds like a dcp repo ticket to me

**Comment by parthshahva** [comment]
Closing as unrelated to upload service

**Comment by jessebrennan** [comment]
It was an accident. Wrong repo. Thanks for closing!
