### ISSUE TITLE
Capture Code Coverage Metrics

### ISSUE THREAD

**Issue by rhiananthony** [HumanCellAtlas/upload-service#399]
This work has shifted to Q4 as NICE TO HAVE work and, as such, may or may not be completed during Q4. It is an objective in the ~Q3~ Q4 epic [Improving Deployment Process for Infrastructure](https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/dcp/420)

## Definition of success
We have 85% code coverage for our unit and integration tests. 

*Please note that there is active discussion about the framing of this definition. This ticket will be updated with any alterations.*

**Comment by maniarathi** [comment]
Currently upload-service's code coverage metrics are available at https://codeclimate.com/github/HumanCellAtlas/upload-service.

Once @rhiananthony and @stahiri have established a centralized location that will contain reporting for all components of the DCP, then this ticket will need to be readdressed to move the metrics there.

**Comment by stahiri** [comment]
@maniarathi I've updated the description of this ticket to reflect the original objective for which it was created, which is actually somewhat misleading based on the ticket title.

**Comment by parthshahva** [comment]
I am closing this ticket. We are at 90% unit test coverage and most api endpoints are covered via the functional tests.
