### ISSUE TITLE
Data files stuck in "validating" in staging

### ISSUE THREAD

**Issue by ESapenaVentura** [HumanCellAtlas/upload-service#400]
1 fastq file is stuck in validation in staging:
- Submission: https://ui.ingest.staging.data.humancellatlas.org/submissions/detail/5d6cf8e2b73e8700073704e5/overview
- Project_uuid: 3e32b461-1a28-47ed-8dc5-b7d6f8c5fc3f
- File: https://api.ingest.staging.data.humancellatlas.org/files/5d6cf8e6b73e8700073705c4
- Size of file: 48.5 GB

Talking with the Ingest devs, the error that is causing this is an `OutOfMemoryError`. Any idea why this might be happenning?

**Comment by ESapenaVentura** [comment]
Oh well, I tried.

**Comment by parthshahva** [comment]
@ESapenaVentura I don't understand your comment "Oh well, I tried". I am on vacation this week and so have not taken a look at this issue.
