### ISSUE TITLE
Final file seems to take a very long time to validate

### ISSUE THREAD

**Issue by mshadbolt** [HumanCellAtlas/upload-service#404]
I am testing a submission in staging and it seems like files that validate later in the process take longer than those at the start. In particular the last file seems to take inordinately longer than previous files. I don't have any timing evidence to support this but hopefully logs can be checked to test my theory. As an example it seems like the last file of this submission, `HCATisStab7587203_S1_L001_R2_001.fastq.gz` has taken hours, whereas many files were validating simultaneously at the beginning of the submission in a much faster time.

I have anecdotal evidence from @ESapenaVentura that it has happened to him as well recently.

This is the submission: https://ui.ingest.staging.data.humancellatlas.org/submissions/detail?uuid=6b22f0e0-524e-4272-bfcb-99ef73f1f5af

Let me know if you need any further information.

**Comment by mshadbolt** [comment]
Just tried kicking the last file back to draft to see if that would make it validate.

**Comment by mshadbolt** [comment]
I downloaded the file to the ec2 and validated using fastq-info and it took around 10 minutes or so and validates as OK

**Comment by mshadbolt** [comment]
Pinging @parthshahva to make sure it is on your radar. I will be trying submission of this data on staging as soon as it is back up and running

**Comment by parthshahva** [comment]
Hi @mshadbolt thanks for reporting this. I was out most of last week. Please ping the upload area for the new submission once its in progress so that I can monitor

**Comment by mshadbolt** [comment]
I did an upload in the rebuilt staging environment yesterday (https://staging.data.humancellatlas.org/explore/projects/bc2229e7-e330-435a-8c2a-4275741f2c2d / https://ui.ingest.staging.data.humancellatlas.org/projects/detail?uuid=bc2229e7-e330-435a-8c2a-4275741f2c2d). None of the validations got stuck this time. In general I still feel like later files take longer, but this might be my imagination or the disturbance in space time that occurs when you really want something to finish.

On another note, it didn't get picked up by the staging data tracker (https://tracker.staging.data.humancellatlas.org/), but I imagine that is something to do with staging falling over and not yet being brought up fully yet.

**Comment by parthshahva** [comment]
Hi Marion, tracker staging should be fixed in the next hour's run. There was a bug. 

I don't see any evidence for the final file taking longer to validate than the first few files. Validation time is based on two factors 1) size of queue 2) size of file. Thus you can expect files at the end to take longer if there are a lot of files in the validation queue from either the current submission or another submission.

I am closing this issue. Please re-open if anything actionable falls out of this.
