### ISSUE TITLE
Remove GDPR data from upload areas for Spatio-temporal immune zonation of the human kidney

### ISSUE THREAD

**Issue by jlzamanian** [HumanCellAtlas/upload-service#407]
We had a project submitted where part of the data is in violation of GDPR. The project needs to be wiped completely from all components and then the non-restricted data re-ingested under the same project uuid, title, and label.

https://data.humancellatlas.org/explore/projects/abe1a013-af7a-45ed-8c26-f3793c24a1f4
Project uuid: abe1a013-af7a-45ed-8c26-f3793c24a1f4
Project label: KidneySingleCellAtlas

The following submissions have data files in prod upload S3 areas.
Ingest staging was previously wiped.

08/12/19 submission uuid = [483eb0b1-3196-4a72-9f30-4a7aecdd25b4](483eb0b1-3196-4a72-9f30-4a7aecdd25b4)

8/12/19 submission uuid = [1e4fb14d-2380-41db-ae7e-37465de815e6](https://ui.ingest.data.humancellatlas.org/submissions/detail?uuid=1e4fb14d-2380-41db-ae7e-37465de815e6)

08/12/19 submission uuid = [cfac3abc-c5cb-49f8-866e-379748d72001](https://ui.ingest.data.humancellatlas.org/submissions/detail?uuid=cfac3abc-c5cb-49f8-866e-379748d72001)

08/09/19 submission uuid = [e39f4b5a-c2ce-4ac1-89c8-747a20d08e8a](https://ui.ingest.data.humancellatlas.org/submissions/detail?uuid=e39f4b5a-c2ce-4ac1-89c8-747a20d08e8a)

08/09/19 submission uuid = [40972c5f-295a-4e39-9ac8-a1aaca89798f](https://ui.ingest.data.humancellatlas.org/submissions/detail?uuid=40972c5f-295a-4e39-9ac8-a1aaca89798f)

08/12/19 submission uuid = [483eb0b1-3196-4a72-9f30-4a7aecdd25b4](https://ui.ingest.data.humancellatlas.org/submissions/detail?uuid=483eb0b1-3196-4a72-9f30-4a7aecdd25b4)

**Comment by jlzamanian** [comment]
The following submissions were confirmed complete and files were transferred from upload areas.

submission uuid=2afc1a93-f35d-4dec-95b7-7bd54b6da834 went complete on 09/25/19
submission uuid=702313be-fdde-42ea-89a5-bd1b01531736 went complete on 08/14/19
submission uuid=9cfca427-6e22-447a-867e-4d81fdb7391c went complete on 10/03/19
submission uuid=9e1d7bdc-e4a8-4dac-a131-6434aeb15bd0 went complete on 10/03/19

submission uuid=0dc428c1-b30a-4ceb-b64b-a5c08ffe2282 was valid, but no data files were transferred to the upload area on 09/25/19

**Comment by parthshahva** [comment]
All areas have been cleaned out
