### ISSUE TITLE
Write Architecture Document

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/upload-service#41]
https://docs.google.com/document/d/10iv1wS3HB9R5dJb8_Bl_i9VvQZpFp5SMBEUZx6WNprI/edit#

**Comment by sampierson** [comment]
This is almost complete and is ready for review.  Other folks need to write the sections on the Batch Watcher Daemon and Heath Check Daemon as I am not the most familiar with those.

@parthshahva @MDunitz @maniarathi @mweiden please can you read it and add comments/questions.

**Comment by maniarathi** [comment]
Assigning back to you Sam. Finished up the check-summing piece!
