### ISSUE TITLE
log the entire credentials in POST Create

### ISSUE THREAD

**Issue by parthshahva** [HumanCellAtlas/upload-service#43]
Sam's  slack: A thought occurs: something that will make debugging easier in the future is to have access to the complete credentials for an upload area.  Currently I think we generate a new user, craft the credentials but never log them.  If, during POST Create, we log the entire credentials before we return them, we will be able to grab them from the logs and try upload areas from the user’s perspective with the CLI.  Please could you add a ticket for this to ZenHub for upload-area.

**Comment by sampierson** [comment]
Obsoleted by #12
