### ISSUE TITLE
Upload Service Operator Statistics API

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/upload-service#6]
Create a API that returns things like:
Counts of upload areas, files, size consumed, validators running.
Use same API key as Ingest to secure this for now.

**Comment by parthshahva** [comment]
@sampierson is there still a need for an api endpoint? The operator dashboard can provide this data

**Comment by sampierson** [comment]
I guess if the database is up to date, we an dig all of this out of there now.  So yes we can close this.
We should write a script that verifies the database is actually correct, but that's a different ticket.
