### ISSUE TITLE
/version endpoint

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/upload-service#69]

**Comment by sampierson** [comment]
Return JSON including:
SemVer version number
Git commit?

**Comment by sampierson** [comment]
We need to write a file that the Chalice app can return data from, when deploying.
It would be good if the checksum daemon also logged its version when running.

**Comment by parthshahva** [comment]
This involves pulling out more recent git tag during deployment and storing somewhere where lambda can read it. Calvin is starting to look into this. Sync with him to determine /version response format.
