### ISSUE TITLE
Put a queue between S3 and checksum-daemon

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/upload-service#81]

**Comment by parthshahva** [comment]
@parthshahva add requirements

**Comment by parthshahva** [comment]
@MDunitz Add requirements we discussed IRL here please. Thanks!

**Comment by MDunitz** [comment]
1. S3 -> SQS trigger added to tf
- secondary queue for failures
- add ticket to deal with events added to the failure queue

2. SQS -> lambda trigger added to tf
3. Package checksum daemon in tf
- zip file packaging and make commands for deployment
- permissions
- make command to deploy new zip file

4. Code clean up (remove domovio/chalice for checksum daemon)
5. Performance testing (tune requirements)
